/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    'quote-attachments': QuoteAttachment;
    'quote-submissions': QuoteSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'quote-attachments': QuoteAttachmentsSelect<false> | QuoteAttachmentsSelect<true>;
    'quote-submissions': QuoteSubmissionsSelect<false> | QuoteSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    siteSettings: SiteSetting;
    quoteForm: QuoteForm;
    servicesPage: ServicesPage;
    aboutPage: AboutPage;
    workPage: WorkPage;
    productPage: ProductPage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    quoteForm: QuoteFormSelect<false> | QuoteFormSelect<true>;
    servicesPage: ServicesPageSelect<false> | ServicesPageSelect<true>;
    aboutPage: AboutPageSelect<false> | AboutPageSelect<true>;
    workPage: WorkPageSelect<false> | WorkPageSelect<true>;
    productPage: ProductPageSelect<false> | ProductPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Main project name used in the admin, cards, and page content.
   */
  title: string;
  /**
   * Public URL for the project page. Example: fingerspelling-with-machine-learning
   */
  slug: string;
  /**
   * Old numeric project ID used to redirect routes like /projects/1 to the new slug URL.
   */
  legacyId?: string | null;
  /**
   * Short labels shown under cards and used for project context.
   */
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Choose which filter tabs this project should appear under on /work and the homepage.
   */
  workFilters?: ('Products' | 'Experiences' | 'Branding')[] | null;
  /**
   * Main thumbnail image used across listing cards and summaries.
   */
  image: number | Media;
  /**
   * Default card shape used in normal project grids and homepage cards.
   */
  aspectRatio: 'portrait' | 'landscape' | 'square';
  /**
   * Larger card shape used only in the featured layout near the top of the /work page.
   */
  featuredAspectRatio: 'portrait' | 'landscape' | 'square';
  /**
   * Small label shown above the hero title.
   */
  heroLabel: string;
  /**
   * Main large heading for the project page.
   */
  heroTitle: string;
  /**
   * Short supporting line under the hero title.
   */
  heroSubtitle: string;
  /**
   * Short summary used for metadata and as an editorial intro to the project.
   */
  heroSummary?: string | null;
  /**
   * External link opened by the main CTA button on the detail page. Leave empty to fall back to /contact.
   */
  launchUrl?: string | null;
  /**
   * Structured project details shown near the top of the case study.
   */
  introMeta: {
    /**
     * Text shown on the main overview button.
     */
    launchLabel: string;
    /**
     * Example: Campaign, Product, Experience, Brand Platform.
     */
    type: string;
    client: string;
    /**
     * Short summary of what was made. Example: Brand system, website, motion toolkit.
     */
    deliverables: string;
  };
  /**
   * Compact label/value facts shown in the overview strip.
   */
  overview?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opening editorial text blocks shown below the overview strip.
   */
  intro?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Large lead image used in the hero artwork and the first showcase block.
   */
  primaryShowcase: {
    image: number | Media;
    alt: string;
    label?: string | null;
  };
  /**
   * Step-by-step timeline that explains how the project moved from discovery to launch.
   */
  process?:
    | {
        /**
         * Example: 01, 02, 03.
         */
        phase: string;
        label: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Main case-study chapters. Each section includes text, an image, and layout settings.
   */
  sections?:
    | {
        eyebrow: string;
        title: string;
        body?:
          | {
              paragraph: string;
              id?: string | null;
            }[]
          | null;
        image: number | Media;
        imageAlt: string;
        /**
         * Choose whether the image appears on the left or right side of the section.
         */
        imageLayout: 'left' | 'right';
        /**
         * Visual tone of the section wrapper.
         */
        tone?: ('light' | 'navy') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Results shown in the impact section. Example: Engagement uplift, conversion rate, reach.
   */
  impactMetrics?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Fast multi-image gallery field. Use this when you want to upload or select several gallery images at once. The public page will use each media item's alt text and caption.
   */
  galleryMedia?: (number | Media)[] | null;
  /**
   * Advanced gallery overrides. Use this only when you need per-image text different from the media library values.
   */
  gallery?:
    | {
        image: number | Media;
        alt: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Quotes shown in the testimonial carousel.
   */
  testimonials?:
    | {
        quote: string;
        author: string;
        role: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Palette chips displayed in the color story section. Optionally assign each swatch to a project-page theme role below.
   */
  colors?:
    | {
        /**
         * Example: #0A1B3F
         */
        hex: string;
        name: string;
        /**
         * Optional. Choose exactly what this swatch controls on the project page. If you leave roles empty, the legacy fallback still applies in order: 1 accent, 2 secondary, 3 background, 4 foreground.
         */
        themeRole?: ('accent' | 'secondary' | 'background' | 'foreground' | 'showcase') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Short label/value items displayed near the bottom of the project page.
   */
  credits?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Choose projects to show in the related projects section.
   */
  relatedProjects?: (number | Project)[] | null;
  /**
   * When enabled, the project page and shared chrome (header, menu, footer) will adopt colors from the ordered palette below. Color 1 = accent, Color 2 = secondary, Color 3 = background, Color 4 = foreground. Additional colors are display-only.
   */
  inheritThemeFromPalette?: boolean | null;
  themePreferenceConfigured?: boolean | null;
  /**
   * Public pages only show projects with a published date.
   */
  publishedAt?: string | null;
  /**
   * Lower numbers appear first in project listings and the /work page.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-attachments".
 */
export interface QuoteAttachment {
  id: number;
  alt?: string | null;
  fieldName?: string | null;
  submission?: (number | null) | QuoteSubmission;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-submissions".
 */
export interface QuoteSubmission {
  id: number;
  status: 'new' | 'inReview' | 'closed';
  sourcePage: string;
  submittedAt: string;
  submitterName: string;
  submitterEmail: string;
  submitterCompany?: string | null;
  preferredContactMethod?: string | null;
  answers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  summaryText: string;
  attachments?: (number | QuoteAttachment)[] | null;
  notificationState: 'pending' | 'sent' | 'failed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'quote-attachments';
        value: number | QuoteAttachment;
      } | null)
    | ({
        relationTo: 'quote-submissions';
        value: number | QuoteSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  legacyId?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  workFilters?: T;
  image?: T;
  aspectRatio?: T;
  featuredAspectRatio?: T;
  heroLabel?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  heroSummary?: T;
  launchUrl?: T;
  introMeta?:
    | T
    | {
        launchLabel?: T;
        type?: T;
        client?: T;
        deliverables?: T;
      };
  overview?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  intro?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  primaryShowcase?:
    | T
    | {
        image?: T;
        alt?: T;
        label?: T;
      };
  process?:
    | T
    | {
        phase?: T;
        label?: T;
        desc?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?:
          | T
          | {
              paragraph?: T;
              id?: T;
            };
        image?: T;
        imageAlt?: T;
        imageLayout?: T;
        tone?: T;
        id?: T;
      };
  impactMetrics?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  galleryMedia?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        label?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        id?: T;
      };
  colors?:
    | T
    | {
        hex?: T;
        name?: T;
        themeRole?: T;
        id?: T;
      };
  credits?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  relatedProjects?: T;
  inheritThemeFromPalette?: T;
  themePreferenceConfigured?: T;
  publishedAt?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-attachments_select".
 */
export interface QuoteAttachmentsSelect<T extends boolean = true> {
  alt?: T;
  fieldName?: T;
  submission?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-submissions_select".
 */
export interface QuoteSubmissionsSelect<T extends boolean = true> {
  status?: T;
  sourcePage?: T;
  submittedAt?: T;
  submitterName?: T;
  submitterEmail?: T;
  submitterCompany?: T;
  preferredContactMethod?: T;
  answers?: T;
  summaryText?: T;
  attachments?: T;
  notificationState?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  internalName?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  canonicalUrl?: string | null;
  /**
   * Internal notes for editors - not visible on site
   */
  statusNote?: string | null;
  blocks?:
    | (
        | {
            blockName?: string | null;
            anchorId?: string | null;
            isVisible?: boolean | null;
            /**
             * Select which hero layout to render. Current uses the video fields below. Creative uses the Creative Hero settings.
             */
            variant?: ('current' | 'creative') | null;
            eyebrow?: string | null;
            headlineRotator?:
              | {
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            desktopVideo?: (number | null) | Media;
            mobileVideo?: (number | null) | Media;
            posterImage?: (number | null) | Media;
            scrollCueLabel?: string | null;
            minHeightVariant?: ('standard' | 'tall') | null;
            overlayStyle?: ('none' | 'light' | 'dark') | null;
            /**
             * CMS-driven content for the Creative hero variant.
             */
            creative?: {
              kicker?: string | null;
              headline?: string | null;
              highlight?: string | null;
              body?: string | null;
              subcopy?: string | null;
              primaryCtaLabel?: string | null;
              primaryCtaHref?: string | null;
              secondaryCtaLabel?: string | null;
              secondaryCtaHref?: string | null;
              layoutVariant?: ('split' | 'stacked') | null;
              mediaSide?: ('right' | 'left') | null;
              textAlign?: ('left' | 'center') | null;
              backgroundStyle?: ('soft' | 'none') | null;
              /**
               * Images shown in the hero media sphere. Add at least 1 for best results.
               */
              mediaItems?:
                | {
                    /**
                     * Images show as-is. Videos show a poster/thumbnail in the sphere and play in a modal.
                     */
                    type?: ('image' | 'video') | null;
                    media?: (number | null) | Media;
                    externalUrl?: string | null;
                    videoMedia?: (number | null) | Media;
                    videoUrl?: string | null;
                    /**
                     * Used for the sphere preview. If omitted, the sphere shows a generic video tile.
                     */
                    posterMedia?: (number | null) | Media;
                    posterUrl?: string | null;
                    alt: string;
                    href?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockType: 'hero';
          }
        | {
            blockName?: string | null;
            anchorId?: string | null;
            isVisible?: boolean | null;
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            filterMode?: ('manual' | 'tagBased') | null;
            filterLabels?:
              | {
                  label?: string | null;
                  id?: string | null;
                }[]
              | null;
            projects?: (number | Project)[] | null;
            maxItems?: number | null;
            emptyStateText?: string | null;
            id?: string | null;
            blockType: 'curatedProjects';
          }
        | {
            blockName?: string | null;
            anchorId?: string | null;
            isVisible?: boolean | null;
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            backgroundMediaType?: ('image' | 'video') | null;
            backgroundImage?: (number | null) | Media;
            backgroundVideo?: (number | null) | Media;
            overlayStyle?: ('none' | 'light' | 'dark') | null;
            stats?:
              | {
                  label?: string | null;
                  value?: string | null;
                  supportingText?: string | null;
                  id?: string | null;
                }[]
              | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            id?: string | null;
            blockType: 'featureMedia';
          }
        | {
            blockName?: string | null;
            anchorId?: string | null;
            isVisible?: boolean | null;
            eyebrow?: string | null;
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  id?: string | null;
                  question?: string | null;
                  answer?: string | null;
                  preview?: string | null;
                  deliverables?:
                    | {
                        label?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                }[]
              | null;
            quoteLauncherVariant?: ('standard' | 'inverted') | null;
            quoteLauncherLabel?: string | null;
            id?: string | null;
            blockType: 'faqSpotlight';
          }
        | {
            blockName?: string | null;
            anchorId?: string | null;
            isVisible?: boolean | null;
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            triggerLabel?: string | null;
            themeVariant?: ('primary' | 'secondary') | null;
            id?: string | null;
            blockType: 'quoteLauncher';
          }
        | {
            blockName?: string | null;
            anchorId?: string | null;
            isVisible?: boolean | null;
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            items?:
              | {
                  label?: string | null;
                  value?: string | null;
                  supportingText?: string | null;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockType: 'statsGrid';
          }
        | {
            blockName?: string | null;
            anchorId?: string | null;
            isVisible?: boolean | null;
            eyebrow?: string | null;
            heading?: string | null;
            richText?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            layoutVariant?: ('centered' | 'left' | 'split') | null;
            id?: string | null;
            blockType: 'richTextContent';
          }
        | {
            blockName?: string | null;
            anchorId?: string | null;
            isVisible?: boolean | null;
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            items?:
              | {
                  media?: (number | null) | Media;
                  alt?: string | null;
                  caption?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            layoutVariant?: ('grid' | 'carousel' | 'masonry') | null;
            id?: string | null;
            blockType: 'mediaGallery';
          }
        | {
            blockName?: string | null;
            anchorId?: string | null;
            isVisible?: boolean | null;
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            logos?:
              | {
                  logo?: (number | null) | Media;
                  name?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockType: 'logoStrip';
          }
        | {
            blockName?: string | null;
            anchorId?: string | null;
            isVisible?: boolean | null;
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            themeVariant?: ('standard' | 'inverted') | null;
            id?: string | null;
            blockType: 'ctaBanner';
          }
      )[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  logoWordmarkPrimary?: (number | null) | Media;
  logoWordmarkSecondary?: (number | null) | Media;
  /**
   * Main links shown in the menu.
   */
  navItems?:
    | {
        label?: string | null;
        href?: string | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  quoteTriggerLabel?: string | null;
  mobileMenuLabel?: string | null;
  storiesHref?: string | null;
  /**
   * Choose on which page types the quote CTA button should be hidden.
   */
  showQuoteCtaRules?: {
    hideOnWork?: boolean | null;
    hideOnServices?: boolean | null;
    hideOnAbout?: boolean | null;
    hideOnProduct?: boolean | null;
    hideOnProjects?: boolean | null;
  };
  contactCards?:
    | {
        label?: string | null;
        sublabel?: string | null;
        value?: string | null;
        href?: string | null;
        copyToClipboard?: boolean | null;
        id?: string | null;
      }[]
    | null;
  locations?:
    | {
        city?: string | null;
        addressLines?:
          | {
              line?: string | null;
              id?: string | null;
            }[]
          | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        label?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  privacyLabel?: string | null;
  privacyHref?: string | null;
  backToTopLabel?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quoteForm".
 */
export interface QuoteForm {
  id: number;
  triggerLabelDefault?: string | null;
  dialogTitle?: string | null;
  dialogDescription?: string | null;
  summaryHeading?: string | null;
  summaryIntro?: string | null;
  submitButtonLabel?: string | null;
  successMessage?: string | null;
  submissionEmailRecipients?:
    | {
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  submissionEmailSubjectPrefix?: string | null;
  steps?:
    | {
        id?: string | null;
        indexLabel?: string | null;
        navLabel?: string | null;
        title?: string | null;
        description?: string | null;
        /**
         * Optional branching rules for this entire step. Leave empty to always show the step.
         */
        visibilityRules?:
          | {
              dependsOnField?: string | null;
              operator?: ('equals' | 'notEquals' | 'includes' | 'notIncludes' | 'isEmpty' | 'isNotEmpty') | null;
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        fields?:
          | {
              id?: string | null;
              name?: string | null;
              type?:
                | (
                    | 'text'
                    | 'textarea'
                    | 'email'
                    | 'phone'
                    | 'singleSelect'
                    | 'multiSelect'
                    | 'radio'
                    | 'checkboxGroup'
                    | 'fileUpload'
                  )
                | null;
              label?: string | null;
              helperText?: string | null;
              placeholder?: string | null;
              required?: boolean | null;
              defaultValue?: string | null;
              includeInSummary?: boolean | null;
              width?: ('full' | 'half' | 'third') | null;
              options?:
                | {
                    label?: string | null;
                    value?: string | null;
                    id?: string | null;
                  }[]
                | null;
              validation?: {
                minLength?: number | null;
                maxLength?: number | null;
                minSelections?: number | null;
                maxSelections?: number | null;
                pattern?: string | null;
                allowedFileMimeTypes?:
                  | {
                      mimeType?: string | null;
                      id?: string | null;
                    }[]
                  | null;
                maxFileSizeMb?: number | null;
                maxFiles?: number | null;
              };
              visibilityRules?:
                | {
                    dependsOnField?: string | null;
                    operator?: ('equals' | 'notEquals' | 'includes' | 'notIncludes' | 'isEmpty' | 'isNotEmpty') | null;
                    value?: string | null;
                    id?: string | null;
                  }[]
                | null;
            }[]
          | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesPage".
 */
export interface ServicesPage {
  id: number;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  canonicalUrl?: string | null;
  /**
   * Legacy: used by the Current hero variant.
   */
  heroTitle?: string | null;
  /**
   * Legacy: used by the Current hero variant.
   */
  heroBody?: string | null;
  /**
   * Select a hero variant. Current uses the legacy fields above. Creative uses the Creative Hero settings.
   */
  hero?: {
    isVisible?: boolean | null;
    variant?: ('current' | 'creative') | null;
    creative?: {
      kicker?: string | null;
      headline?: string | null;
      highlight?: string | null;
      body?: string | null;
      subcopy?: string | null;
      primaryCtaLabel?: string | null;
      primaryCtaHref?: string | null;
      secondaryCtaLabel?: string | null;
      secondaryCtaHref?: string | null;
      layoutVariant?: ('split' | 'stacked') | null;
      mediaSide?: ('right' | 'left') | null;
      textAlign?: ('left' | 'center') | null;
      backgroundStyle?: ('soft' | 'none') | null;
      mediaItems?:
        | {
            media?: (number | null) | Media;
            externalUrl?: string | null;
            alt: string;
            href?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  serviceCategories?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  serviceSections?:
    | {
        /**
         * Used for anchor links (e.g. 'branding').
         */
        sectionId: string;
        eyebrow: string;
        title: string;
        body: string;
        linkLabel: string;
        /**
         * Selects which illustration style renders for this section.
         */
        illustration: 'products' | 'experiences' | 'branding';
        cards?:
          | {
              title: string;
              subtitle: string;
              /**
               * Decorative art style shown on the card. Does not change card copy.
               */
              art: 'confetti-watch' | 'youtube-play' | 'bear-frame' | 'vr-fans' | 'split-rings' | 'residenta-pack';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  shinyThings: {
    eyebrow: string;
    title: string;
    body: string;
  };
  awardColumns?:
    | {
        awards?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage".
 */
export interface AboutPage {
  id: number;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  canonicalUrl?: string | null;
  /**
   * Legacy: used by the Current hero variant.
   */
  heroTitle?: string | null;
  /**
   * Legacy: used by the Current hero variant.
   */
  heroBody?: string | null;
  /**
   * Select a hero variant. Current uses the legacy hero fields above. Creative uses the Creative Hero settings.
   */
  hero?: {
    isVisible?: boolean | null;
    variant?: ('current' | 'creative') | null;
    creative?: {
      kicker?: string | null;
      headline?: string | null;
      highlight?: string | null;
      body?: string | null;
      subcopy?: string | null;
      primaryCtaLabel?: string | null;
      primaryCtaHref?: string | null;
      secondaryCtaLabel?: string | null;
      secondaryCtaHref?: string | null;
      layoutVariant?: ('split' | 'stacked') | null;
      mediaSide?: ('right' | 'left') | null;
      textAlign?: ('left' | 'center') | null;
      backgroundStyle?: ('soft' | 'none') | null;
      mediaItems?:
        | {
            media?: (number | null) | Media;
            externalUrl?: string | null;
            alt: string;
            href?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  jumpLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  locations?:
    | {
        city: string;
        country: string;
        timezone: string;
        mapUrl: string;
        address: string;
        id?: string | null;
      }[]
    | null;
  codeOfHonor?: {
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
    items?:
      | {
          /**
           * Internal unique key for this value card. Keep stable after publishing.
           */
          itemId: string;
          index: string;
          title: string;
          body: string;
          /**
           * Selects the visual style paired with this item.
           */
          art?:
            | (
                | 'be-nice'
                | 'powers-for-good'
                | 'try-the-truth'
                | 'enjoy-the-ride'
                | 'speak-up-and-listen'
                | 'solve-the-problem'
                | 'help-each-other'
                | 'team-up'
              )
            | null;
          id?: string | null;
        }[]
      | null;
  };
  mondayteers?: {
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
    team?:
      | {
          name: string;
          city: string;
          role: string;
          /**
           * Selects the abstract visual treatment on the team card.
           */
          art?:
            | (
                | 'art1'
                | 'art2'
                | 'art3'
                | 'art4'
                | 'art5'
                | 'art6'
                | 'art7'
                | 'art8'
                | 'art9'
                | 'art10'
                | 'art11'
                | 'art12'
                | 'art13'
                | 'art14'
                | 'art15'
                | 'art16'
                | 'art17'
                | 'art18'
                | 'art19'
                | 'art20'
                | 'art21'
                | 'art22'
                | 'art23'
                | 'art24'
                | 'art25'
                | 'art26'
                | 'art27'
                | 'art28'
                | 'art29'
                | 'art30'
              )
            | null;
          accentLabel: string;
          id?: string | null;
        }[]
      | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workPage".
 */
export interface WorkPage {
  id: number;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  canonicalUrl?: string | null;
  /**
   * Select a hero variant. Current uses the legacy fields below. Creative uses the Creative Hero settings.
   */
  hero?: {
    isVisible?: boolean | null;
    variant?: ('current' | 'creative') | null;
    creative?: {
      kicker?: string | null;
      headline?: string | null;
      highlight?: string | null;
      body?: string | null;
      subcopy?: string | null;
      primaryCtaLabel?: string | null;
      primaryCtaHref?: string | null;
      secondaryCtaLabel?: string | null;
      secondaryCtaHref?: string | null;
      layoutVariant?: ('split' | 'stacked') | null;
      mediaSide?: ('right' | 'left') | null;
      textAlign?: ('left' | 'center') | null;
      backgroundStyle?: ('soft' | 'none') | null;
      mediaItems?:
        | {
            media?: (number | null) | Media;
            externalUrl?: string | null;
            alt: string;
            href?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * Legacy: used by the Current hero variant.
   */
  heroTitle?: string | null;
  /**
   * Legacy: used by the Current hero variant.
   */
  heroBody?: string | null;
  /**
   * Each filter needs a display label and a value. Value should match one of: Products, Experiences, Branding.
   */
  filterLabels?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional projects to pin near the top of the work page.
   */
  featuredProjects?: (number | Project)[] | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productPage".
 */
export interface ProductPage {
  id: number;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  canonicalUrl?: string | null;
  /**
   * Direct video URL for the hero background media.
   */
  heroVideoUrl?: string | null;
  heroTitleLines?:
    | {
        line?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Select a hero variant. Current uses the legacy video + title lines above. Creative uses the Creative Hero settings.
   */
  hero?: {
    isVisible?: boolean | null;
    variant?: ('current' | 'creative') | null;
    creative?: {
      kicker?: string | null;
      headline?: string | null;
      highlight?: string | null;
      body?: string | null;
      subcopy?: string | null;
      primaryCtaLabel?: string | null;
      primaryCtaHref?: string | null;
      secondaryCtaLabel?: string | null;
      secondaryCtaHref?: string | null;
      layoutVariant?: ('split' | 'stacked') | null;
      mediaSide?: ('right' | 'left') | null;
      textAlign?: ('left' | 'center') | null;
      backgroundStyle?: ('soft' | 'none') | null;
      mediaItems?:
        | {
            media?: (number | null) | Media;
            externalUrl?: string | null;
            alt: string;
            href?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  introEyebrow: string;
  introParagraphs?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ordered collaboration rows shown in the showcase section.
   */
  collaborations?:
    | {
        name: string;
        projectCount: string;
        tag: string;
        summary: string;
        videoUrl: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Rotating quotes shown in the testimonial strip. Order controls rotation.
   */
  testimonials?:
    | {
        body: string;
        author: string;
        role: string;
        id?: string | null;
      }[]
    | null;
  contact: {
    heading: string;
    body: string;
    email: string;
    briefLabel: string;
    photo?: (number | null) | Media;
    name: string;
    title: string;
    directEmail: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  internalName?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  canonicalUrl?: T;
  statusNote?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              blockName?: T;
              anchorId?: T;
              isVisible?: T;
              variant?: T;
              eyebrow?: T;
              headlineRotator?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              desktopVideo?: T;
              mobileVideo?: T;
              posterImage?: T;
              scrollCueLabel?: T;
              minHeightVariant?: T;
              overlayStyle?: T;
              creative?:
                | T
                | {
                    kicker?: T;
                    headline?: T;
                    highlight?: T;
                    body?: T;
                    subcopy?: T;
                    primaryCtaLabel?: T;
                    primaryCtaHref?: T;
                    secondaryCtaLabel?: T;
                    secondaryCtaHref?: T;
                    layoutVariant?: T;
                    mediaSide?: T;
                    textAlign?: T;
                    backgroundStyle?: T;
                    mediaItems?:
                      | T
                      | {
                          type?: T;
                          media?: T;
                          externalUrl?: T;
                          videoMedia?: T;
                          videoUrl?: T;
                          posterMedia?: T;
                          posterUrl?: T;
                          alt?: T;
                          href?: T;
                          id?: T;
                        };
                  };
              id?: T;
            };
        curatedProjects?:
          | T
          | {
              blockName?: T;
              anchorId?: T;
              isVisible?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              filterMode?: T;
              filterLabels?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              projects?: T;
              maxItems?: T;
              emptyStateText?: T;
              id?: T;
            };
        featureMedia?:
          | T
          | {
              blockName?: T;
              anchorId?: T;
              isVisible?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              backgroundMediaType?: T;
              backgroundImage?: T;
              backgroundVideo?: T;
              overlayStyle?: T;
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    supportingText?: T;
                    id?: T;
                  };
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              id?: T;
            };
        faqSpotlight?:
          | T
          | {
              blockName?: T;
              anchorId?: T;
              isVisible?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    id?: T;
                    question?: T;
                    answer?: T;
                    preview?: T;
                    deliverables?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                  };
              quoteLauncherVariant?: T;
              quoteLauncherLabel?: T;
              id?: T;
            };
        quoteLauncher?:
          | T
          | {
              blockName?: T;
              anchorId?: T;
              isVisible?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              triggerLabel?: T;
              themeVariant?: T;
              id?: T;
            };
        statsGrid?:
          | T
          | {
              blockName?: T;
              anchorId?: T;
              isVisible?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              items?:
                | T
                | {
                    label?: T;
                    value?: T;
                    supportingText?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
            };
        richTextContent?:
          | T
          | {
              blockName?: T;
              anchorId?: T;
              isVisible?: T;
              eyebrow?: T;
              heading?: T;
              richText?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              layoutVariant?: T;
              id?: T;
            };
        mediaGallery?:
          | T
          | {
              blockName?: T;
              anchorId?: T;
              isVisible?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              items?:
                | T
                | {
                    media?: T;
                    alt?: T;
                    caption?: T;
                    href?: T;
                    id?: T;
                  };
              layoutVariant?: T;
              id?: T;
            };
        logoStrip?:
          | T
          | {
              blockName?: T;
              anchorId?: T;
              isVisible?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    name?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        ctaBanner?:
          | T
          | {
              blockName?: T;
              anchorId?: T;
              isVisible?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              themeVariant?: T;
              id?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logoWordmarkPrimary?: T;
  logoWordmarkSecondary?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        id?: T;
      };
  quoteTriggerLabel?: T;
  mobileMenuLabel?: T;
  storiesHref?: T;
  showQuoteCtaRules?:
    | T
    | {
        hideOnWork?: T;
        hideOnServices?: T;
        hideOnAbout?: T;
        hideOnProduct?: T;
        hideOnProjects?: T;
      };
  contactCards?:
    | T
    | {
        label?: T;
        sublabel?: T;
        value?: T;
        href?: T;
        copyToClipboard?: T;
        id?: T;
      };
  locations?:
    | T
    | {
        city?: T;
        addressLines?:
          | T
          | {
              line?: T;
              id?: T;
            };
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  privacyLabel?: T;
  privacyHref?: T;
  backToTopLabel?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quoteForm_select".
 */
export interface QuoteFormSelect<T extends boolean = true> {
  triggerLabelDefault?: T;
  dialogTitle?: T;
  dialogDescription?: T;
  summaryHeading?: T;
  summaryIntro?: T;
  submitButtonLabel?: T;
  successMessage?: T;
  submissionEmailRecipients?:
    | T
    | {
        email?: T;
        id?: T;
      };
  submissionEmailSubjectPrefix?: T;
  steps?:
    | T
    | {
        id?: T;
        indexLabel?: T;
        navLabel?: T;
        title?: T;
        description?: T;
        visibilityRules?:
          | T
          | {
              dependsOnField?: T;
              operator?: T;
              value?: T;
              id?: T;
            };
        fields?:
          | T
          | {
              id?: T;
              name?: T;
              type?: T;
              label?: T;
              helperText?: T;
              placeholder?: T;
              required?: T;
              defaultValue?: T;
              includeInSummary?: T;
              width?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              validation?:
                | T
                | {
                    minLength?: T;
                    maxLength?: T;
                    minSelections?: T;
                    maxSelections?: T;
                    pattern?: T;
                    allowedFileMimeTypes?:
                      | T
                      | {
                          mimeType?: T;
                          id?: T;
                        };
                    maxFileSizeMb?: T;
                    maxFiles?: T;
                  };
              visibilityRules?:
                | T
                | {
                    dependsOnField?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesPage_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  canonicalUrl?: T;
  heroTitle?: T;
  heroBody?: T;
  hero?:
    | T
    | {
        isVisible?: T;
        variant?: T;
        creative?:
          | T
          | {
              kicker?: T;
              headline?: T;
              highlight?: T;
              body?: T;
              subcopy?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              layoutVariant?: T;
              mediaSide?: T;
              textAlign?: T;
              backgroundStyle?: T;
              mediaItems?:
                | T
                | {
                    media?: T;
                    externalUrl?: T;
                    alt?: T;
                    href?: T;
                    id?: T;
                  };
            };
      };
  serviceCategories?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  serviceSections?:
    | T
    | {
        sectionId?: T;
        eyebrow?: T;
        title?: T;
        body?: T;
        linkLabel?: T;
        illustration?: T;
        cards?:
          | T
          | {
              title?: T;
              subtitle?: T;
              art?: T;
              id?: T;
            };
        id?: T;
      };
  shinyThings?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  awardColumns?:
    | T
    | {
        awards?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  canonicalUrl?: T;
  heroTitle?: T;
  heroBody?: T;
  hero?:
    | T
    | {
        isVisible?: T;
        variant?: T;
        creative?:
          | T
          | {
              kicker?: T;
              headline?: T;
              highlight?: T;
              body?: T;
              subcopy?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              layoutVariant?: T;
              mediaSide?: T;
              textAlign?: T;
              backgroundStyle?: T;
              mediaItems?:
                | T
                | {
                    media?: T;
                    externalUrl?: T;
                    alt?: T;
                    href?: T;
                    id?: T;
                  };
            };
      };
  jumpLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  locations?:
    | T
    | {
        city?: T;
        country?: T;
        timezone?: T;
        mapUrl?: T;
        address?: T;
        id?: T;
      };
  codeOfHonor?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        items?:
          | T
          | {
              itemId?: T;
              index?: T;
              title?: T;
              body?: T;
              art?: T;
              id?: T;
            };
      };
  mondayteers?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        team?:
          | T
          | {
              name?: T;
              city?: T;
              role?: T;
              art?: T;
              accentLabel?: T;
              id?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workPage_select".
 */
export interface WorkPageSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  canonicalUrl?: T;
  hero?:
    | T
    | {
        isVisible?: T;
        variant?: T;
        creative?:
          | T
          | {
              kicker?: T;
              headline?: T;
              highlight?: T;
              body?: T;
              subcopy?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              layoutVariant?: T;
              mediaSide?: T;
              textAlign?: T;
              backgroundStyle?: T;
              mediaItems?:
                | T
                | {
                    media?: T;
                    externalUrl?: T;
                    alt?: T;
                    href?: T;
                    id?: T;
                  };
            };
      };
  heroTitle?: T;
  heroBody?: T;
  filterLabels?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  featuredProjects?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productPage_select".
 */
export interface ProductPageSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  canonicalUrl?: T;
  heroVideoUrl?: T;
  heroTitleLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  hero?:
    | T
    | {
        isVisible?: T;
        variant?: T;
        creative?:
          | T
          | {
              kicker?: T;
              headline?: T;
              highlight?: T;
              body?: T;
              subcopy?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              layoutVariant?: T;
              mediaSide?: T;
              textAlign?: T;
              backgroundStyle?: T;
              mediaItems?:
                | T
                | {
                    media?: T;
                    externalUrl?: T;
                    alt?: T;
                    href?: T;
                    id?: T;
                  };
            };
      };
  introEyebrow?: T;
  introParagraphs?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  collaborations?:
    | T
    | {
        name?: T;
        projectCount?: T;
        tag?: T;
        summary?: T;
        videoUrl?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        body?: T;
        author?: T;
        role?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        heading?: T;
        body?: T;
        email?: T;
        briefLabel?: T;
        photo?: T;
        name?: T;
        title?: T;
        directEmail?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}